[build]
  base = "/"
  publish = "public"
  command = "npm run build:ci"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.3"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
