[build]
  base = "/"
  publish = "public"
  command = "npm run build:ci"
  environment = {NODE_VERSION = "14.15.3", RUBY_VERSION="2.6.2"}

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "/archive/*"
  to = "/article/:splat"
  status = 302

[[redirects]]
  from = "/article/2020/08/14/default-http-config"
  to = "/article/2020-08-14-default-http-config"
  status = 302

[[redirects]]
  from = "/article/2020/08/08/custom-domain"
  to = "/article/2020-08-08-custom-domain"
  status = 302

[[redirects]]
  from = "/article/2020/07/26/false-start"
  to = "/article/2020-07-26-false-start"
  status = 302

[[redirects]]
  from = "/article/2020/07/21/intro"
  to = "/article/2020-07-21-intro"
  status = 302

