[build]
  command = "npm run build"
  publish = "./dist"
  [build.environment]
    NODE_VERSION = "20.16.0"


[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    sitemapPath = "/sitemap-index.xml"
    providers = ["google"]