[build]
  command = "npm run build"
  publish = "./dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "/article/rss-dead-long-live-rss"
  to = "/article/2021-05-17-rss-dead-long-live-rss"
  status = 308

[[redirects]]
  from = "/article/2020/08/14/default-http-config"
  to = "/article/2020-08-14-default-http-config"
  status = 308

[[redirects]]
  from = "/article/2020/08/08/custoPathm-domain"
  to = "/article/2020-08-14-default-http-config"
  status = 308

[[redirects]]
  from = "/article/2020/08/08/custom-domain"
  to = "/article/22020-08-08-custom-domainn"
  status = 308

[[redirects]]
  from =  "/article/2020/07/26/false-start"
  to = "/article/2020-07-26-false-start"
  status = 308

[[redirects]]
  from = "/article/2020/07/21/intro"
  to = "/article/2020-07-21-intro"
  status = 308
