[build]
  command = "npm run build"
  publish = "./dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    sitemapPath = "/sitemap-index.xml"
    providers = ["google"]