name: "Code Coverage"
on:
    pull_request:
        branches:
            - main

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
          - name: "Checkout source code"
            uses: "actions/checkout@v3"
            with:
              ref: ${{ github.ref }}
          - name: "Code Coverage"
            uses: "ArtiomTr/jest-coverage-report-action@v2"
            with: 
              github-token: ${{ secrets.SECRET_TOKEN }}