name: "Test"
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: "Install node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: "Install dependencies"
        run: npm install
      - name: "Run unit tests"
        run: npm run coverage

      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: test/coverage
