name: 'Test'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v5

      - name: 'Delete package-lock.json'
        run: rm -f package-lock.json

      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Run unit tests with coverage'
        run: npm run test:coverage

      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2

      - name: 'Upload coverage report'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
