name: "Test"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - ${{ github.head_ref }}
          # TODO add main branch once this is merged - "main"

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4.1.7"
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: ".tool-versions"

      - name: "Install dependencies"
        run: npm install

      - name: "Run unit tests with coverage"
        run: npm run coverage

      - name: "Upload coverage report"
        uses: actions/upload-artifact@v4.3.6
        with:
          name: coverage-${{ matrix.branch }}
          path: test/coverage

      # TODO move reporting to a separate workflow
      - name: "Report coverage on pull request"
        id: "coverage"
        uses: "ArtiomTr/jest-coverage-report-action@v2.3.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
