name: 'Report Test Coverage'

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v5

      - name: 'Download test coverage'
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: List downloaded files
        run: |
          ls -R coverage
          cat coverage/coverage-summary.json || echo "No summary file"

      - name: 'Report test coverage on pull request'
        uses: davelosert/vitest-coverage-report-action@v2
