name: 'Report Licenses'

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  license-report:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v6

      - name: 'Setup tools and dependencies'
        uses: ./.github/actions/setup-tools

      - name: 'Generate license report'
        id: generate-report
        run: pnpm run licenses:html

      - name: 'Upload license report artifact'
        uses: actions/upload-artifact@v7
        with:
          name: license-report
          path: license-report.html

      - name: 'Sanitize license report'
        id: sanitize-report
        run: |
          LICENSE_REPORT=$(node ./scripts/license-report-cleaner.mjs license-report.html)
          echo "LICENSE_REPORT<<EOF" >> $GITHUB_ENV
          echo "$LICENSE_REPORT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 'Report licenses on pull request'
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          header: license
          message: |
            ## License Report

            A license report has been generated.

            <details>
              <summary>Click to expand the full report</summary>
              
              ${{ env.LICENSE_REPORT }}
            </details>

            You can also download the report as an artifact from the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
